export const passwords = [
        {name: "eremita"},
        {name: "konformizm"},
        {name: "harpagon"},
        {name: "pretensjonalny"},
        {name: "hummus"},
        {name: "eskapizm"},
        {name: "demagogia"},
        {name: "antropomorfizm"},
        {name: "paradoks"},
        {name: "wykusz"},
        {name: "apopleksja"},
        {name: "eteryczny"},
        {name: "utracjusz"},
        {name: "mitrężyć"},
        {name: "dekadencja"},
        {name: "imponderabilia"},
        {name: "prokrastynacja"},
        {name: "egzaltacja"},
        {name: "imputować"},
        {name: "personifikacja"},
        {name: "śryż"},
        {name: "trychotomia"},
        {name: "kuriozum"},
        {name: "majuskuła"},
        {name: "szezlong"}
];
